feat: add versioning workflow for releases
Nullify-Platform/nullify-grafana-datasource pull request #17
Opened 2024-02-19 08:12 UTC by kevinydzhu

## Description

Please include a summary of the change with relevant motivation and context

## Linked Issues & PRs

- resolves <insert-issue-link>
- relates to <insert-pr-link>

[GitHub Issue Linking Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Checklist

- [ ] I have added one of the `patch`, `minor`, `major` or `no-release` labels
- [ ] I have linked an issue from this repository using the **Development** option
- [ ] I have performed a self-review of my own code
- [ ] I have checked for redundant or commented out code
- [ ] I have commented my code where I can't make it self-documenting
- [ ] I have made corresponding changes to the documentation
- [ ] I have added any appropriate tests

2024-02-19 08:24 UTC, tim-thacker-nullify requested changes

2024-02-19 08:24 UTC, tim-thacker-nullify commented on .github/workflows/ci-require-labels.yml
we probably don't need this action if we are going to trigger releases when there is a change to the package.json > version field

2024-02-19 08:24 UTC, tim-thacker-nullify commented on .github/workflows/ci-require-labels.yml
we could make the first step of the release action check if there is a git tag for the value of the version field in package.json and create a release/tag if there isn't. thoughts?

2024-02-19 11:31 UTC, kevinydzhu commented on .github/workflows/ci-require-labels.yml
The workflow in this repo is engineered to mirror the workflow in all other Nullify repos: 
label the PR (major, minor, patch, no-release) => merge => release zip is created with the version number set in package.json and plugin.json + git tag created.
The version number in the repo would remain 0.0.0

I'm unopinionated on whether versioning should happen at a repo level or a package level. Existing infra is built around the above and so happy to go with this.

2024-02-19 23:12 UTC, tim-thacker-nullify commented on .github/workflows/ci-require-labels.yml
This is the first npm package we are releasing so i'm fine with changing the release pipeline to make it work better with the way npm packages do things.

To me it seems preferable to have the version in package.json to match the github release version which is why i suggested the above.

You have more experience with NPM packages than me so happy to let you make the call.
Go packages don't have a version in the go.mod, the whole package management system works off git tags instead of a centralised registry which is the big difference here.

2024-02-20 08:54 UTC, kevinydzhu commented on .github/workflows/ci-require-labels.yml
This isn't an npm package. The reasons I'm down to keep the existing versioning system are:
- We're not publishing to the npm register.
- We do not expect non-grafana applications to consume the code in this repo.
- We also do not expect external code maintainers so I'm happy to keep unimportant code deployment processes the same.

2024-02-20 08:55 UTC, tim-thacker-nullify commented on .github/workflows/ci-require-labels.yml
okay sounds good

2024-02-20 08:55 UTC, tim-thacker-nullify approved these changes

2024-02-20 10:36 UTC, merged