feat: repo selector
Nullify-Platform/nullify-grafana-datasource pull request #21
Opened 2024-02-21 15:53 UTC by kevinydzhu

## Description

Please include a summary of the change with relevant motivation and context

## Linked Issues & PRs

- resolves <insert-issue-link>
- relates to <insert-pr-link>

[GitHub Issue Linking Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

## Checklist

- [ ] I have added one of the `patch`, `minor`, `major` or `no-release` labels
- [ ] I have linked an issue from this repository using the **Development** option
- [ ] I have performed a self-review of my own code
- [ ] I have checked for redundant or commented out code
- [ ] I have commented my code where I can't make it self-documenting
- [ ] I have made corresponding changes to the documentation
- [ ] I have added any appropriate tests

2024-02-21 15:55 UTC, kevinydzhu commented
API Endpoint does not support comma separated githubRepositoryId
![CleanShot 2024-02-22 at 02 54 17](https://github.com/Nullify-Platform/nullify-grafana-datasource/assets/6396885/cf6b7538-2c78-437d-8db0-5fd0d4bb739a)

and requires multiple query parameter entries:
![CleanShot 2024-02-22 at 02 53 00](https://github.com/Nullify-Platform/nullify-grafana-datasource/assets/6396885/8da9989c-ff3c-45fb-b7e3-b86c6e2af027)


githubRepositoryId should also be renamed githubRepositoryIds

2024-03-04 02:36 UTC, tim-thacker-nullify requested changes

2024-03-04 02:36 UTC, tim-thacker-nullify commented on src/components/VariableQueryEditor.tsx
> +  //   });
are the commented out lined still needed?

2024-03-04 06:28 UTC, kevinydzhu commented on src/module.ts
> +  .setVariableQueryEditor(VariableQueryEditor);
Seems like the suggested classes are still marked as "@alpha -- experimental". Will investigate later.

2024-03-04 06:32 UTC, tim-thacker-nullify approved these changes

2024-03-04 06:34 UTC, merged